[package]
name = "hash_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
hex = "0.4.3"
hex-literal = "0.4.1"
md-5 = "0.10.6"
sha2 = "0.10.8"
